server:
  port: 8585
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/myTestDBDemo
  application:
    name: user-movie-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost