server:
  port: 9000
spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka