server:
  port: 9091
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/myTestDB
  application:
    name: user-authentication-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost